Update comments, draft 1

diff --git a/jenkinsfiles/antora_separate_1 b/jenkinsfiles/antora_separate_1
--- a/jenkinsfiles/antora_separate_1
+++ b/jenkinsfiles/antora_separate_1
@@ -49,7 +49,7 @@ pipeline {
                 echo "export ORGANIZATION=${ORGANIZATION}" >> jenkinsjobinfo.sh
                 echo "export ONLY_BUILD_ON_DOCS_MODIFICATION=false" >> jenkinsjobinfo.sh
                 echo "export PATH_TO_DOCS=libs/${REPONAME}/doc" >> jenkinsjobinfo.sh
-                echo "export ALWAYS_NOTIFY=true" >> jenkinsjobinfo.sh
+                echo "export ALWAYS_NOTIFY=false" >> jenkinsjobinfo.sh
                 '''
             }
         }
@@ -398,15 +398,27 @@ pipeline {
                 }
                 script {
 
+                  TIMESTAMP = """${sh(
+                  returnStdout: true,
+                  script: '#!/bin/bash \n' + 'date -u +"%Y-%m-%d-%H-%M-%S"'
+                 )}"""
+
                   NOTIFIED_BEFORE = """${sh(
                   returnStdout: true,
                   script: '#!/bin/bash \n' + 'source jenkinsjobinfo.sh; if grep ${ORGANIZATION}-${REPONAME}-${CHANGE_ID}-sent /jenkinsfilecache/pr_notification_list ; then echo -n true; else echo -n false; fi'
                  )}"""
 
+                 if (NOTIFIED_BEFORE == "true") {
+                     COMMENT_ID = """${sh(
+                     returnStdout: true,
+                     script: '#!/bin/bash \n source jenkinsjobinfo.sh; detected_id=$(grep ${ORGANIZATION}-${REPONAME}-${CHANGE_ID}-sent /jenkinsfilecache/pr_notification_list | sed -nE 's/^.*-.*-.*-.*-(.*)$/\1/p'); echo -n ${detected_id} '
+                 )}"""
+
+                 }
                         commenttext = "An automated preview of the documentation is available at [https://${env.CHANGE_ID}.${env.DNSREPONAME}.${env.PRTEST}.cppalliance.org/${PATH_TO_DOCS}/html/index.html](https://${env.CHANGE_ID}.${env.DNSREPONAME}.${env.PRTEST}.cppalliance.org/${PATH_TO_DOCS}/html/index.html)"
 
                     if (ALWAYS_NOTIFY == "false") { 
-                        commenttext = commenttext + "\n\nIf more commits are pushed to the pull request, the docs will rebuild at the same URL."
+                        commenttext = commenttext + "\n\nIf more commits are pushed to the pull request, the docs will rebuild at the same URL.\n\n${TIMESTAMP}"
                     }
 
                     // Per-repo customizations
@@ -419,21 +431,24 @@ pipeline {
                     if ( (ALWAYS_NOTIFY == "true") || (NOTIFIED_BEFORE == "false")) {
                         pullRequest.comment(commenttext)
                     }
-
+                    // Update the PR comment
+                    if ( (ALWAYS_NOTIFY == "false") && (NOTIFIED_BEFORE == "true")) {
+                        pullRequest.editComment(COMMENT_ID, commenttext)
+                    }
                  }
 
                  sh '''#!/bin/bash
                  set -x
                  source jenkinsjobinfo.sh
-                 COMMENT_ID=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$ORGANIZATION/$REPONAME/issues/${CHANGE_ID}/comments | jq '.[] | select(.body|test("An automated preview of the documentation")) | .id' | tail -n 1)
-                 re='^[0-9]+$'
-                 if ! [[ $COMMENT_ID =~ $re ]] ; then
-                    echo "error: COMMENT_ID is not a number"
-                    COMMENT_ID="unset"
-                 fi
                  if grep ${ORGANIZATION}-${REPONAME}-${CHANGE_ID}-sent /jenkinsfilecache/pr_notification_list; then
                      echo "Already noted"
                  else
+                     COMMENT_ID=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$ORGANIZATION/$REPONAME/issues/${CHANGE_ID}/comments | jq '.[] | select(.body|test("An automated preview of the documentation")) | .id' | tail -n 1)
+                     re='^[0-9]+$'
+                     if ! [[ $COMMENT_ID =~ $re ]] ; then
+                        echo "error: COMMENT_ID is not a number"
+                        COMMENT_ID="unset"
+                     fi
                      echo "${ORGANIZATION}-${REPONAME}-${CHANGE_ID}-sent-${COMMENT_ID}" >> /jenkinsfilecache/pr_notification_list
                  fi
                  '''
diff --git a/jenkinsfiles/standard_libraries_1 b/jenkinsfiles/standard_libraries_1
--- a/jenkinsfiles/standard_libraries_1
+++ b/jenkinsfiles/standard_libraries_1
@@ -342,9 +342,14 @@ pipeline {
                  if grep ${ORGANIZATION}-${REPONAME}-${CHANGE_ID}-sent /jenkinsfilecache/pr_notification_list; then
                      echo "Already noted"
                  else
-                     echo "${ORGANIZATION}-${REPONAME}-${CHANGE_ID}-sent" >> /jenkinsfilecache/pr_notification_list
+                     COMMENT_ID=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$ORGANIZATION/$REPONAME/issues/${CHANGE_ID}/comments | jq '.[] | select(.body|test("An automated preview of the documentation")) | .id' | tail -n 1)
+                     re='^[0-9]+$'
+                     if ! [[ $COMMENT_ID =~ $re ]] ; then
+                        echo "error: COMMENT_ID is not a number"
+                        COMMENT_ID="unset"
+                     fi
+                     echo "${ORGANIZATION}-${REPONAME}-${CHANGE_ID}-sent-${COMMENT_ID}" >> /jenkinsfilecache/pr_notification_list
                  fi
-                 '''
 
             }
         }
